[env:esp32c3devkit]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BME280 Library@^2.3.0
	mikalhart/TinyGPSPlus@^1.1.0
