[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
upload_protocol = esptool

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

lib_deps =
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit BME280 Library@^2.3.0
